### ISSUE TITLE
Include toggling task and list nature to the cycle

### ISSUE THREAD

**Issue by hmijail** [ebullient/obsidian-task-collector#456]
(Not sure if this is a bug or a feature request)

I was hoping that the plugin would allow me to cycle out of having a checkbox at all. And the popup says "bksp to remove []", so sounds perfect. However, pressing backspace doesn't remove anything. In fact, while the popup is present, every key I press and anywhere I click seems to just toggle between `[ ]` and `[x]`, even though my cycle is defined as ` /x-`. 

Using a hotkey for the command "Task Collector (TC): Mark with next" does go through my defined cycle, but it'd be great to be able to also remove the checkbox as part of the cycle. (Maybe even the bullet?)

Is this a bug or am I missing something?

**Comment by ebullient** [comment]
Hmm. I use a hotkey with the modal.

If I'm on a line with a checkbox, and use the hotkey to open the modal, and use backspace, the checkbox is (in fact) removed. 

If I am in Live Preview or Reading mode, and I have the click handler active, and I click the checkbox so that the modal pops up, if I type/use backspace, the checkbox is removed.

![Screen Recording 2024-04-22 at 8 53 05 AM](https://github.com/ebullient/obsidian-task-collector/assets/808713/29f400db-4e43-4c49-bae3-cf1817af8f26)

Cycle will only move within the cycle. It won't remove the checkbox as part of that cycle.

> "In fact, while the popup is present, every key I press and anywhere I click seems to just toggle between [ ] and [x], even though my cycle is defined as  /x-." 

That sounds like a configuration problem or a conflict. Please double check the plugins you're using (and the version). There is another plugin that forked from mine and thus also has this modal, but it works a little differently.
